@CharacterChronicleAPI_HostAddress = https://localhost:7059

POST {{CharacterChronicleAPI_HostAddress}}/api/dandd5echaracter
Content-Type: application/json

{
  "characterName":"Xorad",
  "characterLevel":"1",
  "currentXP":"0",
  "currentGold":"5000",
  "characterDescription":"A powerful wizard",
  "age":"50"
  
}

###
